# Generated by Django 3.2.4 on 2021-09-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Page', '0002_page_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='file',
        ),
        migrations.AddField(
            model_name='page',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='files/img'),
        ),
    ]
